### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by dudung** [python-ffmpegio/python-ffmpegio-plugin-mpl#2]
+ Code
```
import numpy as np
from matplotlib import pyplot as plt
import ffmpegio

np.random.seed(0)
fig, ax = plt.subplots(figsize=(9, 4),dpi=300)
ln, = ax.plot([])
ax.set_xlim([0, 1000])
ax.set_ylim([-1, 1])
ax.grid(True)

with ffmpegio.open(
  "writer_test.mp4", # output file name
  "wv", # open file in write-video mode
  1, # framerate in frames/second
  pix_fmt="yuv420p", # specify the pixel format (default is yuv444p)
  overwrite=True
) as writer:
    for i in range(20):
        x = np.arange(1000)
        t = np.random.randn(1000)
        y = np.sin(2 * np.pi * t)
        ln.set_data(x, y)
        writer.write(fig)
```
+ Error messages https://github.com/dudung/graclussep2/blob/main/devel/video/animation_0_not_work.ipynb
  - The last one \
    ![image](https://github.com/user-attachments/assets/9bf6ef62-1db2-4263-b0c8-07385232f7f6)

**Comment by tikuma-lsuhsc** [comment]
@dudung

Do you have the matplotlib plugin installed? (I may not have specified that on the SO)

```
pip install ffmpegio-plugin-mpl
```

Perhaps more descriptive error is in order, but your error imply that.

**Comment by dudung** [comment]
Yes, I have previously installed `matplotlib`, @tikuma-lsuhsc. But not `ffmpegio-plugin-mpl`. I will try install the last and report it.

```
(tf) M:\edu-flow-lake>pip show matplotlib
Name: matplotlib
Version: 3.8.4
Summary: Python plotting package
Home-page: https://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: matplotlib-users@python.org
License: PSF
Location: V:\tf\Lib\site-packages
Requires: contourpy, cycler, fonttools, kiwisolver, numpy, packaging, pillow, pyparsing, python-dateutil
Required-by: jupyterthemes, seaborn

(tf) M:\edu-flow-lake>pip show ffmpegio-plugin-mpl
WARNING: Package(s) not found: ffmpegio-plugin-mpl

(tf) M:\edu-flow-lake>pip show ffmpegio
Name: ffmpegio
Version: 0.10.0.post0
Summary: Media I/O with FFmpeg and NumPy array
Home-page:
Author:
Author-email:
License: GPL-2.0 License
Location: V:\tf\Lib\site-packages
Requires: ffmpegio-core, numpy
Required-by:
```

**Comment by tikuma-lsuhsc** [comment]
Yep, you need the plugin (for now). 

I'm planning on merging all the in-house plugins to the main package in a near future release, but for the time-being, you need to install it separately.

**Comment by dudung** [comment]
Thanks. It works after the plugin installed.

It might be helpful that the information for installing the plugin separately appears in the https://pypi.org/project/ffmpegio/ page.

But I am not sure how the page can be modified without releasing a new version.

**Comment by tikuma-lsuhsc** [comment]
Glad it worked. I'm actually working on merging all the base plugins to the main package for the next release, so you don't have to remember installing the plugins (at least those released by me)
________________________________

**Comment by dudung** [comment]
I hope it will be available soon, @tikuma-lsuhsc. Thanks.
